# Generated by Django 5.2.17 on 2026-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SELLER', 'Vendeur'), ('ADMIN', 'Administrateur'), ('DELIVERY', 'Livreur')], default='CLIENT', max_length=15),
        ),
    ]
