# Generated by Django 5.2.17 on 2026-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_request',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('SELLER', 'Vendeur'), ('ADMIN', 'Administrateur'), ('DELIVERY', 'Livreur')], max_length=15, null=True),
        ),
    ]
