# Generated by Django 5.2.17 on 2026-08-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_deliverers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_sellers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True, help_text="Permet aux Vendeurs/Livreurs d'accéder à leurs espaces."),
        ),
    ]
