# Generated by Django 5.2.17 on 2026-08-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_can_manage_deliverers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_request_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
