# Generated by Django 6.1 on 2026-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_role_request_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text="Permet d'interdire l'accès à un utilisateur suspendu par le Superadmin."),
        ),
    ]
