# Generated by Django 6.1 on 2026-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Permet au Superadmin de masquer ou désactiver un produit.'),
        ),
    ]
